# grpc 配置
grpc:
  host: ""
  port: ":50052"
  name: "order-grpc"

# http 配置
http:
  host: ""
  port: ":9002"
  name: "order-http"

# database config
database:
  mysql:
    host: 175.178.56.152 # Host
    port: 3456 # Port
    username: ygrpc-order # Username
    password: HR7KNaPTAjrpeYyB # Password
    database: ygrpc-order # Database
    charset: utf8mb4 # Charset
    maxIdleCons: 10 # Maximum number of connections in the idle connection pool
    maxOpenCons: 100 # Maximum number of open database connections
    logMode: info # Log level
    enableFileLogWriter: true # Whether to enable log files
    logFilename: sql.log # Log file name

# redis config
redis:
  host: 175.178.56.152
  port: ":6789"
  username: "default"
  password: "qq87708291."
  database: 0
  dial_timeout: 10s
  read_timeout: 10s
  write_timeout: 10s
  pool_timeout: 10s
  pool_size: 10

# tracer
trace:
  tracerName: "order-server-tracer"
  serviceName: "order-server"
  endPoint: "opentelemetry-collector.opentelemetry-system:4317"
