// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"likyam.cn/src/common/client"
	"likyam.cn/src/common/config"
	"likyam.cn/src/common/server"
	"likyam.cn/src/order/service/v1/dao"
	"likyam.cn/src/order/service/v1/server"
)

// Injectors from wire.go:

func InitServer(cfg string) (*Server, error) {
	configConfig := config.NewConfig(cfg)
	db := server.NewMysqlDB(configConfig)
	redisClient := server.NewRedis(configConfig)
	repository := dao.NewRepository(db, redisClient)
	group := server.NewRunGroup()
	logger := server.NewLogger()
	httpServer := NewHttpServer(configConfig)
	userServiceClient, err := client.NewUserClient(configConfig)
	if err != nil {
		return nil, err
	}
	orderServiceServer := serverV1.NewServer(repository, logger, configConfig, userServiceClient)
	grpcServer := NewGrpcServer(orderServiceServer)
	serverServer := NewServer(repository, configConfig, group, logger, httpServer, grpcServer, db)
	return serverServer, nil
}
